homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
  user: 'yourusername'
  password: 'yourpassword'
  client_id: 'zigbee2mqtt'
  include_device_information: true
frontend:
  port: 8080
advanced:
  network_key: GENERATE
serial:
  port: /dev/ttyUSB0
